### ISSUE TITLE
NoMethodError: undefined method `to_json' for {}:Hash

### ISSUE THREAD

**Issue by fabiokr** [dominicsayers/mailchimp_api_v3#12]
Tried to use the gem standalone on `ruby 2.2.5p319` and it raises that when building the payload.

**Comment by dominicsayers** [comment]
Not 100% sure what you mean by "standalone". Could you give me exact steps to reproduce?

**Comment by findkiko** [comment]
I ran into this issue today, for anyone stumbling upon this; the gem has an undeclared dependency on the JSON module. Just add `require 'json'` somewhere in your program to make Hash.to_json available.

**Comment by dominicsayers** [comment]
If anyone cares to do a PR I'd try to merge it promptly
