### ISSUE TITLE
Mailchimp::Exception handling

### ISSUE THREAD

**Issue by ckhatton** [dominicsayers/mailchimp_api_v3#14]
I know it is not an issue, but I hope you might have the time to help me. I am trying to catch the exception that the gem creates when something goes wrong. This is what I have in my controller...

```Ruby
class MembersController < ApplicationController

  rescue_from Mailchimp::Exception, with: :error

  def error

    render json: {
      :status => 'error',
      :success => false,
      :message => error.message,
      :params => params.as_json
    }, status: 500

  end

end
```

Problem is, the JSON is not being rendered.

---

Rails: ~> 5.0.1 | Ruby: 2.3.3 :octocat:

**Comment by dominicsayers** [comment]
Hoping to get time to look at the outstanding issues next week. If I can also look at this question I will.

**Comment by dominicsayers** [comment]
What happens instead? Is the `error` method being used?

**Comment by ckhatton** [comment]
It was, but I have now realised that some fatal exception loop was being created with NewRelic somehow... I couldn't figure out why, so I have removed the `rescue_from` call and gone about it differently...

```Ruby
class MembersController < ApplicationController

  def refer

  . . .

  rescue Mailchimp::Exception::BadRequest

    render json: {
      :status => 'error',
      :success => false,
      # 'error' was being reported as undefined, so I have changed this to a String.
      :message => 'Error!',
      :params => params.as_json
    }, status: 500

  end

end
```

So this now works! But my next question is, how can I grab hold of the helpful message MailChimp returns? I thought originally it would be passed as a variable named 'error'.

> **In this scenario, this is the MailChimp error message:**
>
> "The resource submitted could not be validated. For field-specific details, see the 'errors' array."
>
> **Where's the 'errors' array??**

**Comment by dominicsayers** [comment]
When you make an API call that produces an error (e.g. a `400` status rather than a successful `200`) some information is returned in the response body as JSON. Often this includes an `errors` array showing field-level errors.

Unfortunately `errors` is not passed on by my exception class in this gem. That's probably a bad design decision on my part.

**Comment by dominicsayers** [comment]
There's an example of the raw HTTP transaction here: http://stackoverflow.com/questions/32704462/mailchimp-api-3-0-batch-request-returns-400-invalid-resource-error

**Comment by dominicsayers** [comment]
Contrary to what I said earlier, you can get at the `errors` array easily.

```Ruby
class MembersController < ApplicationController

  def refer

  . . .

  rescue Mailchimp::Exception::BadRequest => e

    render json: {
      :status => 'error',
      :success => false,
      :message => e.message,
      :errors => e.errors,
      :params => params.as_json
    }, status: 500

  end

end
```

**Comment by ckhatton** [comment]
Wonderful! 👏 Thank you so much for taking time out to help!

Maybe that snippet of information could be an useful addition to the README.md, in terms of handling errors.

**Comment by ckhatton** [comment]
I have realised now that the fatal exception loop earlier was because of an undeclared variable (which then caused an error, which then called the error method, which then caused an error, and so on...). Also I remembered that I should really be adding `and return` to my render calls, as good practice.

So this is now what I have in case anyone wants to reference to it:

```Ruby
class MembersController < ApplicationController

  rescue_from Mailchimp::Exception::BadRequest, with: :error

  def error(error)

    puts ''
    puts error.message
    puts ''
    puts error.errors
    puts ''

    render json: {
      :status => 'error',
      :success => false,
      :message => error.message,
      :errors => error.errors,
      :params => params.as_json
    },
    status: 500 and return

  end

end
```

**OR**

```Ruby
class MembersController < ApplicationController

  def refer

  . . .

  rescue Mailchimp::Exception::BadRequest => error

    puts ''
    puts error.message
    puts ''
    puts error.errors
    puts ''

    render json: {
      :status => 'error',
      :success => false,
      :message => error.message,
      :errors => error.errors,
      :params => params.as_json
    },
    status: 500 and return

  end

end
```
