### ISSUE TITLE
Bug: NoMethodError (undefined method `casecmp' for {...}:Hash)

### ISSUE THREAD

**Issue by ckhatton** [dominicsayers/mailchimp_api_v3#18]
I have realised this is a separate issue. I get a fatal error if I use `first_or_create` in an 'each' block where the member **already exists** and has the status **'pending'** in the MailChimp list.

```
NoMethodError (undefined method `casecmp' for {"e6037a062c"=>true, "a25411f7a5"=>false}:Hash):
  
app/services/mailchimp_members_service.rb:63:in `block in refer_members'
.
.
.
```

An exception should really be thrown, such as...

```
Mailchimp::Exception::Duplicate (mail@ckhatton.com is already a list member. Use PUT to insert or update list members.):
.
.
.
```

Taking into account that...

```
@emails = ["mail@ckhatton.com"]
ENV['MAILCHIMP_INTEREST_1ST'] = 'e6037a062c'
ENV['MAILCHIMP_INTEREST_2ND'] = 'a25411f7a5'
```

This is my code...

```ruby
def refer_members

  @emails.each do |email|
    attributes = {
      "email_address": email,
      "status": "pending",
      "interests": {
        ENV['MAILCHIMP_INTEREST_1ST'] => true,
        ENV['MAILCHIMP_INTEREST_2ND'] => false
      }
    }

    MAILCHIMP.lists(ENV['MAILCHIMP_LIST_ID']).members.first_or_create(attributes)
  end

end
```

Again, I have used a similar process as mentioned in the [comment in issue #13](https://github.com/dominicsayers/mailchimp_api_v3/issues/13#issuecomment-284792010) to check if the member already exists.

I have notice it for another block of code I have, where I create a member. I seems to relate to the inner hash of the attributes... I think. I want to check with you first if this is because of this gem, or if I need to report it to MailChimp themselves.

🦑

**Comment by dominicsayers** [comment]
This is a bug in the gem. I never compared members using their interests and the specs didn't envisage this scenario.

You can work around this by doing `first_or_create` using simply the email address, then updating with other attributes if required.

I'll try to release a fix.

**Comment by ckhatton** [comment]
Okay great, thank you.

**Comment by dominicsayers** [comment]
Fixed in https://github.com/dominicsayers/mailchimp_api_v3/tree/v0.2.17
