### ISSUE TITLE
Batch Operation Support

### ISSUE THREAD

**Issue by hooopo** [dominicsayers/mailchimp_api_v3#9]
It seem mailchimp api v3 has support batch operations:
- http://kb.mailchimp.com/api/article/how-to-use-batch-operations

**Comment by onomojo** [comment]
I need this feature. Is anyone working on this yet? If not, I'll be happy to add it.

**Comment by onomojo** [comment]
Hmm, I just found this gem which appears to already supports batch operations: https://github.com/amro/gibbon

**Comment by dominicsayers** [comment]
I started this gem because `gibbon` didn't support the v3 API at the time. I think it now does support v3 so if `gibbon` does what you want then you should use it.

**Comment by dominicsayers** [comment]
Presume @onomojo is happily using Gibbon
